Dockerfile
bratislava/nest-prisma-template pull request #91
Opened 2024-01-09 12:28 UTC by janickoR

- rewritten docker file in order to be more efficient
--> building docker image info:
______new_t | old_t | new_mem | old_mem
build: 18.8s | 45.9s | ~ 714 MB  | ~ 1.82 GB
dev: __16.6s | 22.8s | ~ 501 MB | ~ 1.88 GB
prod: 20.2s | 34.4s  | ~ 502 MB | ~ 614 MB

- package json and docker compose small changes
- added new endpoint for adding user to db - testing purpose (can be droped)

2024-01-09 12:38 UTC, janickoR commented on package.json
> -    "update": "^0.7.4",
this package contains critical vulnerabilities and i wasn't able to updgrade in satisfying way. Also i didn't find a case in which it is needed (if you know some pls tell me) so i decided to drop it.

2024-01-15 08:45 UTC, vidriduch requested changes
Given couple of comments that need to be discussed, but otherwise looks good

2024-01-15 08:45 UTC, vidriduch commented on Dockerfile
> +RUN npm ci --omi=dev --frozen-lockfile
Should this be just `--omi` and not `--omit` ?

2024-01-15 08:45 UTC, vidriduch commented on Dockerfile
> +RUN npm run build
Good question here actually. Should this really be two separate layers or just one? Meaning are these operations decoupled or they always need to be ran together?

More info on layers and what I mean: https://docs.docker.com/develop/develop-images/instructions/#run

2024-01-15 13:51 UTC, vidriduch approved these changes
One more question but otherwise LGTM. Good job 👍

2024-01-15 13:51 UTC, vidriduch commented on Dockerfile
> +# RUN npm prune --production
Why is this line here and commented out?

2024-01-15 14:51 UTC, merged